name: Kiran Babu Muddam - Leetcode

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Sync
      uses: joshcai/leetcode-sync@v1.3
      with:
        github-token: ${{ github.token }}
        leetcode-csrf-token: ${{ secrets.CSRF }}
        leetcode-session: ${{ secrets.SESSION }}
